# Generated by Django 3.2.5 on 2021-07-31 06:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', tinymce.models.HTMLField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
